export const Icon = {
  homeIcon: require('@assets/icons/book.png'),
  profileIcon: require('@assets/icons/user.png'),
  videoIcon: require('@assets/icons/video.png'),
  gameIcon: require('@assets/icons/joystick.png'),
  settingIcon: require('@assets/icons/setting.png'),
  starIcon: require('@assets/icons/star.png'),
  experienceIcon: require('@assets/icons/notebook.png'),
  diplomaIcon: require('@assets/icons/diploma.png'),
  arrowNextIcon: require('@assets/icons/arrow-next.png'),
  treasureIcon: require('@assets/icons/treasure.png'),
  bronzeRankingIcon: require('@assets/icons/bronze.png'),
  cobaltRankingIcon: require('@assets/icons/cobalt.png'),
  cyanRankingIcon: require('@assets/icons/cyan.png'),
  oneIcon: require('@assets/icons/one.png'),
  twoIcon: require('@assets/icons/two.png'),
  threeIcon: require('@assets/icons/three.png'),
  doubleUpArrowIcon: require('@assets/icons/double-up-arrow.png'),
  speakerIcon: require('@assets/icons/speaker.png'),
  closeIcon: require('@assets/icons/close.png'),
  facebookIcon: require('@assets/icons/facebook.png'),
  googleIcon: require('@assets/icons/google-plus.png'),
  phoneIcon: require('@assets/icons/phone-call.png'),
  micIcon: require('@assets/icons/microphone.png'),
};
