export const Icon = {
  homeIcon: require('@assets/icons/book.png'),
  homeIconDisable: require('@assets/icons/book-disable.png'),
  profileIcon: require('@assets/icons/id-card.png'),
  profileIconDisable: require('@assets/icons/id-card-disable.png'),
  rankingIcon: require('@assets/icons/trophy.png'),
  rankingIconDisable: require('@assets/icons/trophy-disable.png'),
  settingIcon: require('@assets/icons/setting.png'),
  starIcon: require('@assets/icons/star.png'),
  experienceIcon: require('@assets/icons/notebook.png'),
  diplomaIcon: require('@assets/icons/diploma.png'),
  arrowNextIcon: require('@assets/icons/arrow-next.png'),
  treasureIcon: require('@assets/icons/treasure.png'),
  bronzeRankingIcon: require('@assets/icons/bronze.png'),
  cobaltRankingIcon: require('@assets/icons/cobalt.png'),
  cyanRankingIcon: require('@assets/icons/cyan.png'),
  goldRankingIcon: require('@assets/icons/gold.png'),
  silverRankingIcon: require('@assets/icons/silver.png'),
  oneIcon: require('@assets/icons/one.png'),
  twoIcon: require('@assets/icons/two.png'),
  threeIcon: require('@assets/icons/three.png'),
  doubleUpArrowIcon: require('@assets/icons/double-up-arrow.png'),
};
